version: "3.9"

services:
  web:
    image: hadiah_mbc1
    ports:
      - "5000:5000"
    depends_on:
      - redis
    secrets:
      - redis_password
    deploy:
      replicas: 1

  redis:
    image: redis:alpine
    command: ["redis-server", "--requirepass", "rahasiaredis123"]
    volumes:
      - redis-data:/data

secrets:
  redis_password:
    file: ./secrets/redis_password.txt

volumes:
  redis-data:
